JOB_NAME:
  "test4"

CALC_OPTION:
  # 画像保存モード
  ## is_save: 画像保存を行う場合は、True
  is_save:
    True
  # 結果取得位置の乱数（乱数を設定しないときは、-1）
  random_seed:
    3

  # 時間項
  ## dt:タイムステップ
  dt: 
    0.0005
  ## calctime:計算時間
  calctime:
    0.1

  # 空間項
  ## dx:x方向の刻み幅
  dx:
    0.05
  ## dy:y方向の刻み幅
  dy:
    0.05
  ## x_max:x方向の計算領域
  x_max:
    5
  ## y_max:y方向の計算領域
  y_max:
    5

  # 熱条件
  ## alpha:熱拡散係数
  alpha:
    1
  ## 初期場
  ### sigma11:2次元ガウス分布の共分散行列11
  sigma11:
    0.3
  ### sigma22:2次元ガウス分布の共分散行列22
  sigma22:
    0.3
  ### sigma12:2次元ガウス分布の共分散行列12
  sigma12:
    &sigma12 0
  ### sigma21:2次元ガウス分布の共分散行列21
  sigma21:
    *sigma12
  ### mean_1:2次元ガウス分布の1方向の平均
  mean_1:
    2.5
  ### mean_2:2次元ガウス分布の1方向の平均
  mean_2:
    2.5

  